# Site Settings
title: Huan Phan Van
email: huphan@siue.edu
description: >
  Huan 1st Site Fixed!
baseurl: "/huanpv"
url: "https://huantianh.github.io"
facebook_username: huantianh
github_username: huantianh
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
